### ISSUE TITLE
ReferenceError: componentHandler is not defined

### ISSUE THREAD

**Issue by jazarja** [delta98/ionic-material-design-lite#55]
I having problem with ionic material design lite when running on Nexus 5, here is my error message.

Any idea how to solve this?
```
ReferenceError: componentHandler is not defined
    at file:///android_asset/www/lib/ionic-material-design-lite/dist/ionic.material-design-lite.min.js:1:555
    at file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:48811:19
    at Object.ionic.Platform.ready (file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:2122:9)
    at Object.self.ready (file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:48809:26)
    at o.hasOwnProperty.t.useMaterialRipple.o.hasOwnProperty.post (file:///android_asset/www/lib/ionic-material-design-lite/dist/ionic.material-design-lite.min.js:1:538)
    at invokeLinkFn (file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:17477:9)
    at nodeLinkFn (file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:16977:11)
    at compositeLinkFn (file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:16368:13)
    at nodeLinkFn (file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:16972:24)
    at compositeLinkFn (file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:16368:13) <button ng-click="validate()" class="button button-clear button-icon ion-checkmark mdl-js-button mdl-js-ripple-effect">
```

**Comment by jazarja** [comment]
Okay, got it.

We need to put <script src="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.js"></script> in the index.html

**Comment by delta98** [comment]
@jazarja for reference what had you not included in the index.html and what method of install did you use?
